version: "3.6"

networks:
  app:
    external: false
    name: ${PROJECT_NAME}-${SERVICE_NAME}

services:

  app:
    image: ${PROJECT_NAME}_${SERVICE_NAME}
    working_dir: /home/node/project/app
    command: "npm start"
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}
    volumes:
      - .:/home/node/project
      - /home/node/project/app/node_modules
      - /home/node/project/shared/node_modules
      - /dev/snd:/dev/snd
    networks:
      - app
    environment:
      - DEBUG=true
      - ENVIRONMENT=default
      - NODE_ENV=production
