version: "3.6"

services:

  build:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: ${PROJECT_NAME}_${SERVICE_NAME}
    working_dir: /home/node/project/app
    command: "npm run build"
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}-build
    volumes:
      - .:/home/node/project
      - /home/node/project/app/node_modules
      - /home/node/project/shared/node_modules
    environment:
      - DEBUG=true
      - ENVIRONMENT=default
      - NODE_ENV=development
